import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className={'p-2'}>
      <Head>
        <title className='font-black'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'p-2'}>
        <h1 className={'p-2'}>
          Welcome to <a href="https://nextjs.org">Matthew Pryor</a>
        </h1>

        <p className='text-red-500 p-4'>
          Get started by editing{' '}
          <code className={'p-2'}>pages/index.tsx</code>
        </p>

        <div className={'p-2'}>
          <a href="https://nextjs.org/docs" className={'p-2'}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={'p-2'}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={'p-2'}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={'p-2'}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={'p-2'}>

      </footer>
    </div>
  )
}

export default Home
